### ISSUE TITLE
recent auth issues? 

### ISSUE THREAD

**Issue by 88gts** [gglockner/teslajson#30]
code and pw have not changed but i have not been able to auth for two days or so. anyone else experiencing this? 

87, in fetch_sso_token
    m = re.search('code=([^&]*)',r.headers['location'])
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by Les-A** [comment]
I too have had this problem for the last couple of days. I'm still using Python 2.7 and I the account only uses the basic authentication - email & password. The last data collected via Teslajson was 2021-05-28 19:05:03 GMT. I was recording data every 60 seconds at that point.

Response contains the following keys:
Server
Content-Type
X-DNS-Prefetch-Control
X-Frame-Options
Strict-Transport-Security
X-Download-Options
X-Content-Type-Options
X-XSS-Protection
X-Request-ID
X-Correlation-ID
Content-Security-Policy
X-Content-Security-Policy
X-WebKit-CSP
ETag
X-Response-Time
X-EdgeConnect-MidMile-RTT
X-EdgeConnect-Origin-MEX-Latency
OriginIP
X-Akamai-Transformed
Vary
Content-Encoding
Date
Content-Length
Connection
Set-Cookie
Origin_hostname

**Comment by AlexanderSidorenko** [comment]
Same here. I was actually about to create an issue myself, but you beat me to it :)
My list of headers in the response is identical.
The last datapoint I have received through Tesla-JSON was on 2021-05-28, 12:04 PST.

**Comment by gglockner** [comment]
Remember folks, this library uses an _undocumented API_. Looks like Tesla changed the API again, and it will take some time to reverse engineer it.

**Comment by gglockner** [comment]
It looks like Tesla [now requires you to complete a CAPTCHA](https://github.com/timdorr/tesla-api/discussions/390). This isn't going to have a quick fix. Again, such is life with an undocumented API.

**Comment by Les-A** [comment]
Thanks Greg, I saw that in the data and did wonder. Best of luck and thanks
for all the work you've done so far.

**Comment by OldGrumpyFart** [comment]
Same exact problem here.

For reference/testing i also
test with tdorssers / TeslaPy (github)

It still works, the one I have was downloaded in Februari.

Would it be possible to snarf the login and wake_up code from TeslaPy ?

In another project they speculated it was the old/wrong USER_AGENT,
when updated their code magically started to work again ...

**Comment by Les-A** [comment]
Started working normally for me again at 2021-06-02 09:15:05 BST. Haven't made any changes. Maybe Tesla has backed out the change (temporarily?).

**Comment by OldGrumpyFart** [comment]
Ditto, suddenly works as before, no changes required.

**Comment by 88gts** [comment]
Auth issues started appearing again yesterday.  Working for anyone else?

**Comment by Les-A** [comment]
Problem started yesterday evening for me again (error references 'location'). It still isn't working now. I then tried TeslaPy and it appears to be working fine so presumably TeslaPy was fixed for the problem even though Tesla appeared to back the change out.

**Comment by spinkb** [comment]
Auth issues here too.  Worked until a 2 or 3 days ago.

**Comment by ivomans** [comment]
Same problem 'KeyError: location' started for me on 2021-07-08.

**Comment by tux43** [comment]
I'm getting the same, anything that can be done? I miss this thing!

`root@masterbot:/config# /config/unlock_car.sh
Traceback (most recent call last):
  File "/config/unlock_car.py", line 4, in <module>
    c = teslajson.Connection('my@email.com', 'andapassword')
  File "/usr/local/lib/python3.9/site-packages/teslajson/teslajson.py", line 66, in __init__
    self.fetch_token(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajson/teslajson.py", line 150, in fetch_token
    self.fetch_sso_token(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajson/teslajson.py", line 123, in fetch_sso_token
    m = re.search('code=([^&]*)',r.headers['location'])
  File "/usr/local/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
`

**Comment by spinkb** [comment]
I changed over to TeslaPy...it handles the captcha and can give you the image to solve manually.  One time action needed as it keeps using a refresh token after that.  Worked for me.  Maybe teslajson can implement the equivalent...

**Comment by tux43** [comment]
Thanks, I’ve just moved over to TeslaPy too, all good.

**Comment by 88gts** [comment]
same, i appreciated the lib. used it to remind my husband that his car needed to be plugged in at night when dead so he wouldn’t take mine. the passive aggressive realist lives on in the memory. thank you!

**Comment by johnbanks1** [comment]
I too am trying TeslaPy - the 2 suggested code snippets and cli.py and menu.py
But in every case I'm geting an error on line 210 of __init__.py
Credentials rejected  Captcha is required  Catcha does not match
Any suggestions most welcome
How do you get an image to solve manually? for example

**Comment by spinkb** [comment]
Ask your questions over on that project, not here.  There is a snippet of source on the main page for TeslaPy showing how to do an alternate captcha solver where you can get the real file.
